"""Add payment method and admin fee fields

Revision ID: 2b26d7660d5d
Revises: f0ef102d4161
Create Date: 2026-02-02 17:24:28.151236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b26d7660d5d'
down_revision = 'f0ef102d4161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_fee', sa.Float(), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_screenshot', sa.String(length=255), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('PENDING', 'PAID', 'CANCELLED', 'FAILED', 'PROCESSING', name='orderstatus'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'PAID', 'CANCELLED', 'FAILED', 'PROCESSING', name='orderstatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
        batch_op.drop_column('payment_screenshot')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('admin_fee')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('admin_fee')

    # ### end Alembic commands ###
