"""add site settings

Revision ID: a4bc5d00aaba
Revises: 73f1bde72fa8
Create Date: 2026-02-03 16:47:37.953624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4bc5d00aaba'
down_revision = '73f1bde72fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_phone', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_setting')
    # ### end Alembic commands ###
